// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWGo35-3ufP8xs65FY31dXx_h0bGxfIag',
    appId: '1:602426551207:web:d70e784e57ce8d2ffc6482',
    messagingSenderId: '602426551207',
    projectId: 'intellibra-ecb00',
    authDomain: 'intellibra-ecb00.firebaseapp.com',
    storageBucket: 'intellibra-ecb00.appspot.com',
    measurementId: 'G-BE0LFEC6Q3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbvj4BpjWr_i1LCG8GbEJksnje1PQf7yA',
    appId: '1:602426551207:android:e09776a6f87224b9fc6482',
    messagingSenderId: '602426551207',
    projectId: 'intellibra-ecb00',
    storageBucket: 'intellibra-ecb00.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbDiY37f54GsHu4ps4szNJDam5YU0RUf0',
    appId: '1:602426551207:ios:0c182b97d05e7d3ffc6482',
    messagingSenderId: '602426551207',
    projectId: 'intellibra-ecb00',
    storageBucket: 'intellibra-ecb00.appspot.com',
    androidClientId: '602426551207-oasoguu01cstpsim9ardn1ivmmiuih77.apps.googleusercontent.com',
    iosClientId: '602426551207-alm0es0ctd0vu425o8578em0evc3ldok.apps.googleusercontent.com',
    iosBundleId: 'anora.intellibra.app.intellibra',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbDiY37f54GsHu4ps4szNJDam5YU0RUf0',
    appId: '1:602426551207:ios:0c182b97d05e7d3ffc6482',
    messagingSenderId: '602426551207',
    projectId: 'intellibra-ecb00',
    storageBucket: 'intellibra-ecb00.appspot.com',
    androidClientId: '602426551207-oasoguu01cstpsim9ardn1ivmmiuih77.apps.googleusercontent.com',
    iosClientId: '602426551207-alm0es0ctd0vu425o8578em0evc3ldok.apps.googleusercontent.com',
    iosBundleId: 'anora.intellibra.app.intellibra',
  );
}
